### ISSUE TITLE
Short story format ?

### ISSUE THREAD

**Issue by taophp** [lise-henry/crowbook#3]
I may use crowbook to format some short stories, with only one md file, so it should be great to have a option to change the output to something adapted : there is only one chapter, one title for both the book and the chapter, no numbering and no blank page to start with.

**Comment by lise-henry** [comment]
Including the md file with "!" allows to hide the chapter in the rendered file (though they still appear in the TOC). E.g:

```
author: Foo
title: Bar

! short_story.md
```
*should* do the trick for current HTML/EPUB output . (PDF/Latex would currently require to change the template file as well, to use "article" class instead of "book", because there is currently no other way to specify it.) However it would indeed be nice to be able to just have one file for the markdown code and the metadata, as you point out in #2

**Comment by taophp** [comment]
I'll try your idea for the epub when I have a minute and let you if it does the trick.

>PDF/Latex would currently require to change the template file as well, to use "article" class instead of "book", because there is currently no other way to specify it.

Yes, that's what I tought.

**Comment by lise-henry** [comment]
`crowbook` can now be called with `--single` to parse a Markdown file that embed its configuration in an inline YAML block. Not closing the bug yet, though, because it would still be nice to have templates (at least for LaTeX) that depend on some options to use different a different class for the document.

**Comment by taophp** [comment]
Great to discover the `--single` option ! I have test it immediately and, yes, it good for me ! Thanks for your work !

A detail to see: as there is no chapter, and that the title is set in the Yaml, the h1 requirement seems redundant in that case. It is not a problem for the PDF output, but the epub failed if the H1 is missing.
In fact, that should be useful for Jekyll: many Jekyll templates (including mines) treat the document title (defined in the Yaml block) separately form the rest of the text. So relying on the h1 tag in the text breaks the template...

**Comment by lise-henry** [comment]
> A detail to consider: as there is no chapter, and that the title is set in the Yaml, the h1 requirement seems redundant in that case. It is not a problem for the PDF output, but the epub failed if the H1 is missing.

This requirement was because I was convinced it would cause problems if the EPUB's manifest and TOC listed a file with an empty title, but apparently it doesn't (it just doesn't appear in the TOC but in that case that's probably what you'd want anyway) so I just removed it.

**Comment by taophp** [comment]
OK, that's great. Now, what I miss the most is the support of the article latex class... to close this bug and definitively adopt Crowbook for my short stories chain.

**Comment by taophp** [comment]
Great! You make my day!
