### ISSUE TITLE
`img` tag with local src url hasn't been imported?

### ISSUE THREAD

**Issue by hustcer** [lise-henry/crowbook#89]
```html
<img src="./img/ferris/does_not_compile.svg" class="ferris-explain" alt="Ferris with a question mark">
```
There is a SVG file from the relative path of current markdown file at `./img/ferris/does_not_compile.svg`, and
It seemed like that the code snippet above was rendered as raw text instead of a html `img` Tag.

Maybe a subset of HTML tags could be supported like `<span>, <br>, <p>, <img>, <pre>, <em>, <strong>` etc.

Other REF: https://www.markdownguide.org/basic-syntax/#html

**Comment by stefan0xC** [comment]
According to the [README](https://github.com/lise-henry/crowbook#input-format) this is intentional:

> Inline HTML, however, is not implemented, and probably won't be, as the goal is to have books that can also be generated in PDF (and maybe ODT).

For HTML and EPUB creation the markdown for images should work just fine:

    ![Ferris with a question mark](./img/ferris/does_not_compile.svg)

The creation of PDF would currently fail because crowbook's PDF rendering does not handle SVG images yet. This would probably require either the usage of a LaTeX package like [svg](https://ctan.org/pkg/svg) or converting the SVG as PNG with a crate like [resvg](https://github.com/RazrFalcon/resvg). It might also be fine to just tell people to use PNG instead of SVG for better interoperability?

**Comment by hustcer** [comment]
@lise-henry Thank you very much. I found it very handy and like it very much. Great work!
